### ISSUE TITLE
3 problems crashing my Angular 18 app

### ISSUE THREAD

**Issue by rafaelcastrodev** [pusherman/ngx-katex#5]
I'm running on Angular 18.0.0
Chrome,

"katex": "^0.16.11",
"ng-katex": "^2.0.3",
"ngx-katex": "^18.0.0",
"@types/katex": "^0.16.7",

3 problems:

1) 
`./node_modules/ngx-katex/fesm2022/ngx-katex.mjs:8:11-23 - Error: export 'render' (imported as 'katex') was not found in 'katex' (possible exports: default)`

2) 
`Error: src/app/home/home.page.html:25:5 - error NG8001: 'ng-katex' is not a known element:

3) 
`Error: node_modules/ng-katex/lib/ng-katex-html.component.d.ts:12:35 - error TS2694: Namespace '"D:/.projetos/ionic/matcoruja/node_modules/@angular/core/index"' has no exported member 'ɵɵComponentDefWithMeta'.
[ng] 12     static ngComponentDef: ɵngcc0.ɵɵComponentDefWithMeta<KatexHtmlComponent, "ng-katex-html", never, { 'html': "html" }, {}, never>;
[ng]                                      ~~~~~~~~~~~~~~~~~~~~~~
[ng] Error: node_modules/ng-katex/lib/ng-katex-paragraph.component.d.ts:6:35 - error TS2694: Namespace '"D:/.projetos/ionic/matcoruja/node_modules/@angular/core/index"' has no exported member 'ɵɵComponentDefWithMeta'.
[ng] 6     static ngComponentDef: ɵngcc0.ɵɵComponentDefWithMeta<KatexParagraphComponent, "ng-katex-paragraph", never, { 'paragraph': "paragraph" }, {}, never>;
[ng]                                     ~~~~~~~~~~~~~~~~~~~~~~
[ng] Error: node_modules/ng-katex/lib/ng-katex.component.d.ts:9:35 - error TS2694: Namespace '"D:/.projetos/ionic/matcoruja/node_modules/@angular/core/index"' has no exported member 'ɵɵComponentDefWithMeta'.
[ng] 9     static ngComponentDef: ɵngcc0.ɵɵComponentDefWithMeta<KatexComponent, "ng-katex", never, { 'equation': "equation", 'options': "options" }, { 'onError': "onError" }, never>;
[ng]                                     ~~~~~~~~~~~~~~~~~~~~~~
[ng] Error: node_modules/ng-katex/lib/ng-katex.directive.d.ts:13:35 - error TS2694: Namespace '"D:/.projetos/ionic/matcoruja/node_modules/@angular/core/index"' has no exported member 'ɵɵDirectiveDefWithMeta'.
[ng] 13     static ngDirectiveDef: ɵngcc0.ɵɵDirectiveDefWithMeta<KatexDirective, "[katex]", never, { 'equation': "katex", 'options': "katex-options" }, { 'onError': "onError" }, never>;
[ng]                                      ~~~~~~~~~~~~~~~~~~~~~~
[ng] Error: node_modules/ng-katex/lib/ng-katex.module.d.ts:8:32 - error TS2694: Namespace '"D:/.projetos/ionic/matcoruja/node_modules/@angular/core/index"' has no exported member 'ɵɵNgModuleDefWithMeta'.
[ng] 8     static ngModuleDef: ɵngcc0.ɵɵNgModuleDefWithMeta<KatexModule, [typeof ɵngcc1.KatexDirective, typeof ɵngcc2.KatexComponent, typeof ɵngcc3.KatexParagraphComponent, typeof ɵngcc4.KatexHtmlComponent], [typeof ɵngcc5.CommonModule], [typeof ɵngcc2.KatexComponent, typeof ɵngcc3.KatexParagraphComponent, typeof ɵngcc4.KatexHtmlComponent]>;
[ng]                                  ~~~~~~~~~~~~~~~~~~~~~
[ng] Error: node_modules/ng-katex/lib/ng-katex.service.d.ts:7:36 - error TS2724: '"D:/.projetos/ionic/matcoruja/node_modules/@angular/core/index"' has no exported member named 'ɵɵInjectableDef'. Did you mean 'ɵgetInjectableDef'?
[ng] 7     static ngInjectableDef: ɵngcc0.ɵɵInjectableDef<KatexService>;`

CONTEXT:

[ng] 1. If 'ng-katex' is an Angular component, then verify that it is part of this module.
[ng] 2. If 'ng-katex' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
[ng] 25     <ng-katex [equation]="equation"></ng-katex>`

I imported exactly as you put on Readme, but got this errors.
My module:
`import { NgxKatexModule } from 'ngx-katex';`

My component:
`equation: string = '\\sum_{i=1}^nx_i';`

If I change the component usage from `<ng-katex` to `<ngx-katex>` I got only the first error.
I installed old package as well. Same result.

The third problem happens when I try to use the KatexOptions. Just to add the import on my component, the app crashes.

Do you know how to solve?

**Comment by cwilsn** [comment]
It looks like Angular 18 support wasn't working.  I've fixed this in the latest version (v19.0.0).  I've also switched it out to be a standalone component so there's no need to import the module anymore.  The readme has been updated to show the correct usage.  (<ngx-katex)

**Comment by cwilsn** [comment]
@rafaelcastrodev - Let me know if you are still having issues with the latest version.

**Comment by rafaelcastrodev** [comment]
My friend, you really respond quickly!!!
Worked perfectly, amazing job!!!
